<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EQ-EQ6283668" ignored="1" name="Default test(failed)" tests="3" failures="1" timestamp="14 Oct 2018 12:45:29 GMT" time="0.063" errors="0">
  <testcase name="secondTestMethod" time="0.014" classname="TstNg.TestRetryTestCases">
    <skipped/>
  </testcase> <!-- secondTestMethod -->
  <testcase name="secondTestMethod" time="0.005" classname="TstNg.TestRetryTestCases">
    <skipped/>
  </testcase> <!-- secondTestMethod -->
  <testcase name="secondTestMethod" time="0.002" classname="TstNg.TestRetryTestCases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TstNg.TestRetryTestCases.secondTestMethod(TestRetryTestCases.java:17)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- secondTestMethod -->
  <testcase name="firstTestMethod" time="0.0" classname="TstNg.TestRetryTestCases">
    <ignored/>
  </testcase> <!-- firstTestMethod -->
</testsuite> <!-- Default test(failed) -->
